### PR TITLE
update for 1198

### PR DESCRIPTION
**Pull request by aviv**
cf. https://github.com/dobtco/screendoor-v2/pull/1198

Todo:
- [x] Site search

### CODE REVIEW

**Comment by aviv** [comment]
@ajb ready for review. The search article is a bit sparse, but not sure what else to put there as it's so simple to use.

**Comment by ajb** [comment]
Everything looks good, but let's do `draft: true` (is that the syntax?) for the search article. Maybe we can enable it laber.

**Comment by aviv** [comment]
Yep, done.

**Comment by aviv** [comment]
Ready for review/merge.

**Pull request merged**
