### PR TITLE
new footer

### LINKED ISSUE #153: Add new landing page footer to knowledge base
See the new footer in dobtco/splash after it's merged to `production`.

### PR DESCRIPTION
**Pull request by aviv**
will close #153

### CODE REVIEW

**Comment by aviv** [comment]
How this looks as of this first draft (preliminary):

**Comment by ajb** [comment]
Thanks for dealing with this, but I'm not in favor of merging. We should aim to solve the root causes of not being able to share these elements, instead of just duplicating our markup everywhere. We have a bunch of different web properties, and duplicating stylesheets and markup is just going to create more work for us in the future, which is why dvl-core exists in the first place.

Ideas for this:

- The landing page footer (and base styles?) should either go into dvl-core, or into some other place where it can be reused

- We should use SASS for the knowledge base, since we're using it everywhere else. If we can't do so, we can always use the compiled version of dvl-core.

- We should probably consider refactoring the styles in the knowledge base to match our global styles elsewhere.

@dobtco/dev: We can all chat about this if you want, but sharing our styles across repos is something I feel strongly that we need to be good about from the outset.

**Comment by aviv** [comment]
I completely agree. The frustration of trying to match styles/markup across different environments with different base styles is not something that we should be dealing with. However, this is kind of a *big issue*, no? As far as I can tell, the landing page stylesheets share nothing in common with dvl-core or Screendoor's. Ideally, it seems like all of our web properties share a set of base stylesheets; additionally, there should be a clear distinction between what is shared and what is specific to that site/app. So this footer, for example, would be a shared component rather than landing-page-specific.

:+1: to [switching the knowledge base over to SASS](https://github.com/dobtco/knowledge_base/issues/158).

**Comment by ajb** [comment]
Sure, it's a "big issue" in the sense that it's been a driver for a lot of our architectural decisions, and it's something that all of our developers should be aware of.

And to clarify, I don't think that our landing pages and our apps need to share the exact same styles -- the requirements for Screendoor's styles are vastly different from the requirements for our splash page -- but we should keep this number at 2, not any higher.

**Comment by kariannemah** [comment]
:+1: I'm in favor of pulling the landing page footer and some of the styles into dvl-core or, better yet, into a separate repo—maybe one for static page styles only?

**Comment by ajb** [comment]
I would recommend just adding to dvl/core for now, but creating a separate manifest: https://github.com/dobtco/dvl-core/tree/master/vendor/assets/stylesheets/dvl

**Comment by ajb** [comment]
I'm working on dvl-core right now, so I'll let you know when I have the footer in there.

**Pull request closed without merging**
