### PR TITLE
Update IE9 support as per https://github.com/dobtco/dobt/issues/1555

### PR DESCRIPTION
**Pull request by ajb**
@kariannemah for review

### CODE REVIEW

**Comment by kariannemah** [comment]
Made a couple of tiny edits. 👌

**Comment by ajb** [comment]
Any idea why Circle is failing all of the sudden?

**Comment by kariannemah** [comment]
When Circle ran `link-checker:dev`, it returned this: 

screen shot 2016-04-25 at 2 46 47 pm

But I can access http://localhost:8080/articles/your_account/dashboard/managing_users.html just fine when I run the server.

**Comment by ajb** [comment]
I'm troubleshooting now.

On Mon, Apr 25, 2016 at 5:49 PM, Kari Mah <notifications@github.com> wrote:

> When Circle ran link-checker:dev, it returned this:
>
> [image: screen shot 2016-04-25 at 2 46 47 pm]
> <https://cloud.githubusercontent.com/assets/970325/14800126/a3e66cd6-0af4-11e6-8df7-a63792f8e011.png>
>
> But I can access
> http://localhost:8080/articles/your_account/dashboard/managing_users.html
> just fine when I run the server.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/pull/292#issuecomment-214538068>
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
Removed it for now. Not worth the headache.

**Pull request merged**
