### PR TITLE
Update knowledge base to dvl-core

### PR DESCRIPTION
**Pull request by jrubenoff**
Again, no big design or code changes. Just trying to avoid regressions.

@aviv, I converted all the FAQs to h3s to improve legibility, but that appears to have broken the table of contents. Any chance you could take a look?

### CODE REVIEW

**Comment by ajb** [comment]
@jrubenoff: can you take a look at the failing specs? It appears to be looking for the `dobt` font:

http://dobt-captured.s3.amazonaws.com/ajb/dobtcoknowledge_base_591_-_CircleCI_2015-07-02_09-54-10.png

I don't think that `/icons` should be included in the `dvl/core` manifest. I'll make a comment over in the dvl-core PR.

**Comment by ajb** [comment]
Looks great! 

- [ ] The combo of `:hover` and `:active`, and `:focus` states on the nav brand text is weird. Should I explain more, or can you see it too?
- [ ] Using bold for hover states in the sidebar is weird IMO, since it makes the link move underneath your cursor (http://dobt-captured.s3.amazonaws.com/ajb/screencast_2015-07-02_10-02-43_0_edited.mp4)

**Comment by aviv** [comment]
Seconding that the hover/active/focus states are not quite right. Contrast is super low here:

**Comment by ajb** [comment]
That's a different issue than the one I was noticing, FWIW

**Comment by aviv** [comment]
- [ ] Seems like far too much spacing here (table of contents `li`s): http://take.ms/kKHio

- [ ] The permalink anchor next to `h2`s is out of alignment (I can look into fixing this, too, just making a note): http://take.ms/ubLRD

- [ ] The footer looks totally misaligned to me: http://take.ms/pluYT

**Comment by jrubenoff** [comment]
I don't see the `.nav_brand` hover state issue. Screenshots might help?

Fixed the other bugs you both mentioned.

**Comment by ajb** [comment]
Looks great. Here's what I mean about nav_brand:

img
img
img
img

This leads to weird behavior, since clicking something invokes these states:

default -> hover -> active -> focus

(i think)

I can try to make a PR if you'd prefer.

**Comment by jrubenoff** [comment]
Just added a focus state for navbar content to `dvl-core`.

**Comment by ajb** [comment]
Thanks, that definitely helps.

This looks good to merge.

**Comment by aviv** [comment]
Looks good to me

**Pull request merged**
