### PR TITLE
Full-width screenshots

### LINKED ISSUE #124: More consistent image widths
Example: http://help.dunked.com/knowledge_base/topics/add-a-new-project

### PR DESCRIPTION
**Pull request by aviv**
Will close #124 

Think this is looking really good. PRing for feedback on image width, how these are looking, etc. before I do them all.

### CODE REVIEW

**Comment by ajb** [comment]
This looks great, we should get @jrubenoff to chime in as well.

My concerns:

- Payload size of our pages, since these pngs are pretty big. We could try lazy-loading them based on scroll position? Or what about using `jpg` instead? The only real reason to use `png` is for transparency, and it's not like we need that...

- Users might find it hard to scroll through a bunch of tall images for the section they're looking for. Do the "On this page" links mitigate this enough?

**Comment by aviv** [comment]
- Will try a few options (including `jpg`s) and see how big these images end up being.

**Comment by aviv** [comment]
As we transition over, I can also make sure that our "On this page" links are as useful as possible, i.e. push any important sections to `h1`s. We could also consider showing `h2`s under "On this page" as well.

**Comment by jrubenoff** [comment]
Lazy-loading would be nice.

You know, the solution here is enforcing a readable line length for content. Here are [The Rules™](http://www.barnesandnoble.com/w/elements-of-typographic-style-robert-bringhurst/1101464013?ean=9780881792058) for future reference:

- 45-75 characters per line is good
- 66 characters per line is ideal
- If you have multiple columns, like in a newspaper, 40-50 characters is best

Then you can keep images from being too tall. See Dunked's help section again, or look at [Flow
s](https://www.getflow.com/support/workspaces/deleting/).

Speaking of that Flow link, constricting the column width also helps you add smaller images that don't look too awkward...

**Comment by ajb** [comment]
img

**Comment by aviv** [comment]
Yeah, I think we could definitely decrease the max line length and at the same time decrease the width of these full-size screenshots, but this is what that looks like:



Seems to me that this makes the lines of text too narrow and the screenshots far too narrow, no?

**Comment by ajb** [comment]
Maybe something in the middle?

**Comment by aviv** [comment]
At a certain point, the text in the full-width screenshots becomes really tiny... here's max ~105 chars, maybe a happy medium?

**Comment by ajb** [comment]
What resolution are you taking the screenshots at? Can we take them at a
lower resolution?

On Wed, Feb 18, 2015 at 4:14 PM, Aviv Nitsan <notifications@github.com>
wrote:

> At a certain point, the text in the full-width screenshots becomes really
> tiny... here's max ~105 chars, maybe a happy medium?
>
>
> <https://camo.githubusercontent.com/540de2b1654ee2b494b41bd66d0ebae3395e9feb/687474703a2f2f74616b652e6d732f3344364c38>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/pull/151#issuecomment-74949130>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by aviv** [comment]
I'm taking them at retina/2, but remember I haven't run any of this stuff through imageoptim or done anything to reduce image size.

**Comment by ajb** [comment]
That's not my question -- I'm asking "how big is your browser window?"

On Wed, Feb 18, 2015 at 4:19 PM, Aviv Nitsan <notifications@github.com>
wrote:

> I'm taking them at retina/2, but remember I haven't run any of this stuff
> through imageoptim or done anything to reduce image size.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/pull/151#issuecomment-74950053>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by aviv** [comment]
Oh, I've been doing 982px because any smaller than that and the project checklist starts looking funky.

**Comment by ajb** [comment]
Gotcha. Fair enough.

On Wed, Feb 18, 2015 at 4:22 PM, Aviv Nitsan <notifications@github.com>
wrote:

> Oh, I've been doing 982px because any smaller than that and the project
> checklist starts looking funky.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/pull/151#issuecomment-74950559>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by aviv** [comment]
Alright, looks like optimized `png`s are actually roughly the same size as `jpg`s saved at ~70%, i.e. **<70k** (and that's without resizing from 952px -> 728px --- still trying to find a good resizing solution that doesn't result in loss of quality), which seems reasonable to me. For comparison, [Dunk's full-width screenshots](https://groovehq.s3.amazonaws.com/uploaded/ALx1miRQ4x1PxUuq954M?1400003856) are ~45k, but they're smaller and look like shit.

**Comment by ajb** [comment]
Cool -- if the optimized pngs are less than 100kb I think that's totally reasonable. (I had just always assumed they were larger...)

As long as the entire page clocks in at under 1MB, I think we're safe. (But less is always better.)

**Comment by aviv** [comment]
@ajb what do you think about this idea? Just a thought, as it seems really silly to do like 5 full-width screenshots for this page. Couldn't get these to work as anchor links with markdown on first pass (something weird with `marked`) but that's an option as well.

**Comment by ajb** [comment]
Not the biggest fan, would much rather have multiple screenshots like in your initial comp.

**Comment by aviv** [comment]
Copy that, I'm tending to agree. Footnotes might not be the best visual model for referencing images in a knowledge base lol.

**Comment by aviv** [comment]
Holding off on taking more screenshots as https://github.com/dobtco/screendoor-v2/pull/1451 is going to make a bunch of these ones that I just took obsolete.

**Comment by ajb** [comment]
That PR is in limbo, I would not wait for it to be resolved in order to do something with this one.

**Comment by aviv** [comment]
Copy that.

**Comment by aviv** [comment]
Running everything through imageoptim now (punting on the resizing, as it's kind of a sticky issue and these images are mostly ~50-75k anyway, so it's not absolutely necessary right now), but then this should be good to merge! We can talk about doing full-width for govmapper/adopta/dashboard too, but that's 1. not as important (I'm assuming) and 2. nowhere near as many screenshots.

**Comment by aviv** [comment]
ok @ajb, care to review?

**Comment by ajb** [comment]
Two images with issues:

- `images/add_field.png` appears to be pointing to the id fields
- `images/allow_edits.png` circle is off

**Comment by ajb** [comment]
This looks really excellent, really happy to get it merged.

**Comment by aviv** [comment]
> images/allow_edits.png circle is off

What do you think about this alternative style:



Just an idea. Ready to merge :beers:

**Comment by ajb** [comment]
dope. i like the current style better, it's more clear.

**Pull request merged**
