### PR TITLE
Shortcuts

### LINKED ISSUE #234: Add pages for Shortcuts
see https://github.com/dobtco/screendoor-v2/pull/2816

### PR DESCRIPTION
**Pull request by kariannemah**
Closes #234.

I wanted to add a new line between the Youtube embed and the first paragraph, but I couldn't figure out how: 
screen shot 2015-11-24 at 8 55 27 am

### CODE REVIEW

**Comment by jrubenoff** [comment]
Copyedited a bit; let me know if that looks good.

**Comment by kariannemah** [comment]
Thanks! Along with light copyediting, I corrected the alt text for some of the screenshots.

**Comment by kariannemah** [comment]
Ready to merge, I think.

**Comment by ajb** [comment]
Skimmed it, looks good. Feel free to merge without me :)

**Comment by jrubenoff** [comment]
:cool:

**Pull request merged**
