### PR TITLE
Revamped content

### PR DESCRIPTION
**Pull request by jrubenoff**
- Minor design improvements
- Totally reworked content for Screendoor and the Dashboard (thanks @kariannemah!)

@ajb, I used the `redirect_from` tag to reference old URLs, as you mentioned.

Two pages still need to be written: "Creating your project page", and "Making data-informed decisions". But everything else is done and ready for review + copyediting.

### CODE REVIEW

**Comment by jrubenoff** [comment]
Also: the rewritten Socrata page is based off #2474.

**Comment by kariannemah** [comment]
Sweet! I'll start editing on Monday. This closes #221, too.

**Comment by ajb** [comment]
Looks good! I added the redirect code, but we should test that we're properly redirecting all of the old URLs before we merge.

What about changing "Your account" to "Account dashboard"? "Your account" isn't really the name of the app. It looks like you might have started to do this already, too: http://take.ms/2LoD0

**Comment by kariannemah** [comment]
Is it just me or is something weird going on in "Adding adoptable things"?

This is the markdown:
> Here's an example of a simple CSV file that you can use to import hydrants:
 
    lat,lng
    37.875271,-122.271025
    37.875271,-122.261025

>You can also include the `name` header:

    lat,lng,name
    37.875271,-122.271025,some hydrant
    37.875271,-122.261025,another hydrant

Here's how it renders (in both Firefox and Chrome):
screen shot 2015-09-03 at 10 49 12 am

Same thing with "Writing your project page":
screen shot 2015-09-03 at 10 52 53 am

**Comment by kariannemah** [comment]
@jrubenoff I've reviewed and edited all the Screendoor pages, plus Adopta and Govmapper, too, because—why not? Can you give the Dashboard pages a quick review, unless you've done so already?

**Comment by kariannemah** [comment]
@jrubenoff As for changing "Your account" to "Account dashboard," I'll defer to your judgment, but I'll make the edits if needed.

**Comment by ajb** [comment]
Notes from call:

- Merge this today, even without "data driven decisions"
- "Your account" stays, but remove anything that says "Account Dashboard" (it's in there currently)

**Comment by jrubenoff** [comment]
@kariannemah Added the "Writing your project page" article. Feel free to merge once everything looks good to you.

**Comment by kariannemah** [comment]
Made a couple edits. 

Looks great!

**Comment by ajb** [comment]
I'll squash + merge.

**Comment by kariannemah** [comment]
:+1:  3cf533d is my last commit.

**Comment by ajb** [comment]
Rebased in https://github.com/dobtco/knowledge_base/pull/230

**Pull request closed without merging**
