### PR TITLE
Update articles with consolidated wizard pages

### LINKED ISSUE #253: Update articles with consolidated wizard pages
https://github.com/dobtco/screendoor-v2/pull/3023

### PR DESCRIPTION
**Pull request by kariannemah**
Closes #253.

@ajb This PR updates the copy on all KB articles that feature the project wizard, but I'm wondering whether to hold off on taking screenshots until the tab layout is live. How close is https://github.com/dobtco/screendoor-v2/pull/3039 to being merged and deployed?

### CODE REVIEW

**Comment by ajb** [comment]
Yes! I really appreciate the mind-reading. This should definitely wait until that's merged.

**Comment by kariannemah** [comment]
:+1: and due credit to @jrubenoff for the reminder

**Comment by ajb** [comment]
#3039 is merged but let's wait on https://github.com/dobtco/screendoor-v2/issues/3050.

**Comment by ajb** [comment]
dobtco/screendoor-v2#3050 has been closed, but not yet deploy to prod. Will plan to do so tomorrow.

**Comment by kariannemah** [comment]
:+1:

**Comment by kariannemah** [comment]
Apologies: the updated "Save this project as a template" screenshot (`templates_1.png`) doesn't technically belong in this PR.

**Comment by ajb** [comment]
Wow, what a PR. Looks fantastic. :ship:

**Pull request merged**
