### PR TITLE
add splash footer

### PR DESCRIPTION
**Pull request by ajb**
let's wait until these `dvl-core` changes get merged into master, but feedback is welcome.

### CODE REVIEW

**Comment by ajb** [comment]
looks like we need a newer version of sass/ruby on circlec?

**Comment by aviv** [comment]
Is that the issue? Looks like both `dvl-core` and `knowledge_base` are using sass version `3.4.12`, no?

**Comment by ajb** [comment]
@aviv: can you give this a final review? I kinda messed up the merge, it should be resolved but a second set of eyes would be good.

@jrubenoff: can you spare 5 minutes to tweak the colors? they don't look too great...

**Comment by aviv** [comment]
- yeah the colors are way too dark IMO

- this is out of alignment I think (the "back to screendoor" link is lower):



- the footer text is much smaller in the knowledge base then on the homepage

- are we sure that we want the large "subscribe" section in the footer? doesn't quite seem appropriate in the knowledge base, but if we want to standardize (and hope some people will subscribe through there), then that makes sense.

**Comment by ajb** [comment]
> yeah the colors are way too dark IMO

Leaving to Josh

> this is out of alignment I think (the "back to screendoor" link is lower):

**Comment by ajb** [comment]
> yeah the colors are way too dark IMO

leaving to Josh

> this is out of alignment I think (the "back to screendoor" link is lower):

Fixing

> the footer text is much smaller in the knowledge base then on the homepage

I'm aware -- that's because the base text size is larger on the homepage. That's fine IMO.

> are we sure that we want the large "subscribe" section in the footer? doesn't quite seem appropriate in the knowledge base, but if we want to standardize (and hope some people will subscribe through there), then that makes sense.

We can remove it no problem, I just thought that it was a good idea.

**Comment by ajb** [comment]
> this is out of alignment I think (the "back to screendoor" link is lower):

Actually, I'm not sure what the issue is there. You're welcome to PR or file an issue on dobtco/dvl-core.

**Comment by aviv** [comment]
OK, sounds good. Also, I'd increase the padding inside the input here (happy to PR later, though):

**Comment by ajb** [comment]
Yeah, see if you can tweak that component inside of dvl-core later, it'll be good to have someone else jump into that codebase :)

**Comment by ajb** [comment]
- removed mailing list form from footer
- tweaked footer color

**Comment by jrubenoff** [comment]
Looks good. Added a sticky footer and constrained the width of the content area.

**Comment by ajb** [comment]
Ty!

**Pull request merged**
