### PR TITLE
explain hiding vs. deleting fields

### LINKED ISSUE #13: Explain "hiding" vs deleting fields
(i'll fill this in later)

### PR DESCRIPTION
**Pull request by aviv**
closes #13

### CODE REVIEW

**Comment by aviv** [comment]
@ajb, ready for R&M.

**Comment by ajb** [comment]
One part that you haven't captured: if there are no responses to a project, the behavior is different. (No dropdown when clicking delete)

**Comment by aviv** [comment]
Hmm, yeah I'm seeing that behavior now, but that seems very strange to me. Why would there being no responses change the fact that I may want to make that field hidden?

**Comment by jrubenoff** [comment]
If there are no responses, there are no consequences to deleting it. Hiding a field lets you remove the field from the form while still keeping the responses you have received.

**Comment by aviv** [comment]
OK makes sense. I guess what's tripping me up is that you can make a field hidden either by checking the box on the left or by hitting the remove button -> dropdown. But I can see how providing the ability to hide the field as an alternative to deleting it makes sense in this situation.

**Comment by aviv** [comment]
OK :+1:

**Comment by ajb** [comment]
lgtm, @aviv: can you squash into one commit and merge?

**Comment by ajb** [comment]
nice squash, yo.

**Pull request merged**
