### PR TITLE
first take of "rules" -> "conditional logic"

### PR DESCRIPTION
**Pull request by ajb**
cf https://github.com/dobtco/screendoor-v2/issues/3556

Still needs screenshots. Probably best to wait until https://github.com/dobtco/screendoor-v2/pull/3567 is merged.

### CODE REVIEW

**Comment by kariannemah** [comment]
Made some slight edits. I labeled this as `todo_upcoming` and will take the screenshots once https://github.com/dobtco/screendoor-v2/pull/3567 is merged.

**Comment by ajb** [comment]
Just shipped this to production. Josh changed from "conditional logic" to "logic".

**Comment by kariannemah** [comment]
Added some new screenshots and changed "conditional logic" to just "logic."

**Comment by ajb** [comment]
:+1:

**Pull request merged**
