### PR TITLE
Update screenshots for new dvl-core

### LINKED ISSUE #215: update screenshots for new dvl-core
cf. https://github.com/dobtco/screendoor-v2/pull/2153

@ajb shall I retake all of our screenshots?

### PR DESCRIPTION
**Pull request by aviv**
closes #215
QA in https://github.com/dobtco/screendoor-v2/issues/2231

### CODE REVIEW

**Comment by aviv** [comment]
- [ ] Retake `blind_fields.png`after issue number 7 in https://github.com/dobtco/screendoor-v2/issues/2231 is fixed (this can happen after merging, though)

**Comment by aviv** [comment]
@kariannemah want to take a quick look?

**Comment by kariannemah** [comment]
lgtm! :+1: :+1: :+1:

**Comment by aviv** [comment]
Thanks!
@ajb I'll let you merge.

**Comment by ajb** [comment]
Looks great. Thanks so much for retaking all of these!

**Pull request merged**
