### PR TITLE
add messages guidelines / TOS

### PR DESCRIPTION
**Pull request by ajb**
img

### CODE REVIEW

**Comment by jrubenoff** [comment]
Regarding placement, could we make this the start of a Screendoor-specific Terms of Service?

**Comment by ajb** [comment]
Sure, but what else do you see being part of it?

**Comment by jrubenoff** [comment]
Never mind, sorry. Thought this was going in `splash` instead of the knowledge base.

If I'm encountering this feature for the first time, I'd also want to see examples of good and bad messages.

This page makes it clear how someone _shouldn't_ use this feature... so what _should_ they be doing?

**Comment by ajb** [comment]
Would you or Kari be willing to tackle that?

On Fri, Dec 11, 2015 at 7:04 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Never mind, sorry. Thought this was going in splash instead of the
> knowledge base.
>
> If I'm encountering this feature for the first time, I'd also want to see
> examples of good and bad messages.
>
> This page makes it clear how someone *shouldn't* use this feature... so
> what *should* they be doing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/pull/236#issuecomment-164084993>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by kariannemah** [comment]
Yes, I’ll take a first pass.

On December 11, 2015 at 4:10:45 PM, Adam Becker (notifications@github.com) wrote:

Would you or Kari be willing to tackle that?

On Fri, Dec 11, 2015 at 7:04 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Never mind, sorry. Thought this was going in splash instead of the
> knowledge base.
>
> If I'm encountering this feature for the first time, I'd also want to see
> examples of good and bad messages.
>
> This page makes it clear how someone *shouldn't* use this feature... so
> what *should* they be doing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/pull/236#issuecomment-164084993>
> .
>



--
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
Merging this for now so that we can merge https://github.com/dobtco/screendoor-v2/pull/2903. Created a new issue for adding good / bad messages: https://github.com/dobtco/knowledge_base/issues/237

**Pull request merged**
