### PR TITLE
add notes on manual responses + confirmation emails

### PR DESCRIPTION
**Pull request by ajb**
did this in GitHub's editor so I haven't previewed in-app.

### CODE REVIEW

**Comment by kariannemah** [comment]
:+1: I reworded the "Importing responses" FAQ. What do you think?

screen shot 2016-03-22 at 5 04 22 pm

**Comment by ajb** [comment]
There's also a "Screendoor field" for respondent email. I think you might
have missed that?

On Tue, Mar 22, 2016 at 8:06 PM, Kari Mah <notifications@github.com> wrote:

> Assigned #288 <https://github.com/dobtco/knowledge_base/pull/288> to @ajb
> <https://github.com/ajb>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/knowledge_base/pull/288#event-599565017>
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by kariannemah** [comment]
The Screendoor respondent email field is what I meant by "Respondent email field." I wanted to clarify "any new respondents" and account for responses imported _without_ email address—hence the "Even if..." 

But I don't feel strongly about it! If you think it's too confusing, feel free to revert my commits.

**Comment by ajb** [comment]
Ah, sorry. I thought you were talking about key fields. I think it might be a little jargony.

**Comment by ajb** [comment]
Merging anyway, I think it's fine :)

**Pull request merged**
